services:
  - type: web
    name: finance-tracker
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_DATABASE
        value: finance_tracker
      - key: MONGODB_URI
        sync: false
